### ISSUE TITLE
No links to learning about languages 05AB1E Actually Brachylog Husk Jelly ?

### ISSUE THREAD

**Issue by Russtopia** [abrudz/lb#8]
Hi, love your APL bar, it has helped me doing the Dyalog and GNU APL tutorials.
However, I am curious about these other language modes in your bar though -- are these other APL-like languages, or some esoteric 'expert' modes for doing APL development with special vocabularies?

I would request adding links to the languages, if they are other ones we could build and try, if applicable, or to appropriate FAQs for what these are. Thanks!

PS. Apologies if this is not the proper channel to contact you. I could not seem to find any email link in the via or via github.

**Comment by abrudz** [comment]
Great idea! (Btw, only Jelly is related to APL, by way of J.)

**Comment by Russtopia** [comment]
> Great idea! (Btw, only Jelly is related to APL, by way of J.)

:) Thank you. I like trying obscure languages but could not find links to most of the languages. I would love to try some of them if possible.

**Comment by abrudz** [comment]
The first word in the heading for each page is a link:
![image](https://user-images.githubusercontent.com/10961427/99947164-76a3d400-2d6f-11eb-989d-bbd884d3f399.png)

**Comment by Russtopia** [comment]
Ah, thank you!
